import type { Level } from '../../lib/types';

const PREFIX = 'red';

export const red: Level = {
  id: 'red',
  label: 'Red — Stage 2',
  order: 1,
  color: 'text-red-500',
  decks: [
    {
      id: 'phonics',
      title: 'Letter Sounds',
      description: 'Single sounds for sounding out',
      emoji: '🔤',
      color: 'bg-rose-500',
      cards: [
        { word: 's', emoji: '🐍', hint: 'snake' },
        { word: 'a', emoji: '🍎', hint: 'apple' },
        { word: 't', emoji: '🍅', hint: 'tomato' },
        { word: 'p', emoji: '🐷', hint: 'pig' },
        { word: 'i', emoji: '🐛', hint: 'insect' },
        { word: 'n', emoji: '🪺', hint: 'nest' },
        { word: 'm', emoji: '🌙', hint: 'moon' },
        { word: 'd', emoji: '🦆', hint: 'duck' },
        { word: 'g', emoji: '🐐', hint: 'goat' },
        { word: 'o', emoji: '🍊', hint: 'orange' },
        { word: 'c', emoji: '🐱', hint: 'cat' },
        { word: 'k', emoji: '🔑', hint: 'key' },
        { word: 'e', emoji: '🥚', hint: 'egg' },
        { word: 'u', emoji: '☂️', hint: 'umbrella' },
        { word: 'r', emoji: '🐇', hint: 'rabbit' },
        { word: 'h', emoji: '🎩', hint: 'hat' },
        { word: 'b', emoji: '🐝', hint: 'bee' },
        { word: 'f', emoji: '🐟', hint: 'fish' },
        { word: 'l', emoji: '🦁', hint: 'lion' },
      ].map((c) => ({ ...c, id: `${PREFIX}.phonics.${c.word}` })),
    },
    {
      id: 'tricky',
      title: 'Tricky Words',
      description: 'Words to recognise',
      emoji: '✨',
      color: 'bg-amber-500',
      cards: [
        { word: 'a' },
        { word: 'and' },
        { word: 'the' },
        { word: 'to' },
        { word: 'I' },
        { word: 'no', emoji: '🚫' },
        { word: 'go', emoji: '🟢' },
        { word: 'in', emoji: '📥' },
        { word: 'is' },
        { word: 'it' },
        { word: 'up', emoji: '⬆️' },
        { word: 'mum', emoji: '👩' },
        { word: 'dad', emoji: '👨' },
        { word: 'look', emoji: '👀' },
        { word: 'see', emoji: '👁️' },
        { word: 'can', emoji: '🥫' },
        { word: 'my' },
        { word: 'we' },
      ].map((c) => ({ ...c, id: `${PREFIX}.tricky.${c.word}` })),
    },
    {
      id: 'characters',
      title: 'Characters',
      description: 'The Biff, Chip & Kipper crew',
      emoji: '👨‍👩‍👧‍👦',
      color: 'bg-sky-500',
      cards: [
        { word: 'Biff', emoji: '👧' },
        { word: 'Chip', emoji: '👦' },
        { word: 'Kipper', emoji: '👶' },
        { word: 'Floppy', emoji: '🐕' },
        { word: 'Mum', emoji: '👩' },
        { word: 'Dad', emoji: '👨' },
        { word: 'Wilf', emoji: '🧒' },
        { word: 'Wilma', emoji: '👧🏽' },
      ].map((c) => ({ ...c, id: `${PREFIX}.characters.${c.word}` })),
    },
    {
      id: 'nouns',
      title: 'First Words',
      description: 'Picture words for blending',
      emoji: '🐱',
      color: 'bg-emerald-500',
      cards: [
        { word: 'cat', emoji: '🐱' },
        { word: 'dog', emoji: '🐶' },
        { word: 'sun', emoji: '☀️' },
        { word: 'bus', emoji: '🚌' },
        { word: 'hat', emoji: '🎩' },
        { word: 'bed', emoji: '🛏️' },
        { word: 'ball', emoji: '⚽' },
        { word: 'fish', emoji: '🐟' },
      ].map((c) => ({ ...c, id: `${PREFIX}.nouns.${c.word}` })),
    },
  ],
};
